name: Run KAN Emotional Character with LLaMA 3.1 8B Instruct

on:
  push:
    branches:
      - main

jobs:
  run-kan-emotional-character:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
        pip install git+https://github.com/huggingface/transformers

    - name: Run KAN Emotional Character script
      env:
        HF_CLIENT_ID: ${{ secrets.HF_CLIENT_ID }}
        HF_CLIENT_SECRET: ${{ secrets.HF_CLIENT_SECRET }}
      run: |
        python kan_emotional_character_llama_hf.py

    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: kan-emotional-character-logs
        path: kan_emotional_character.log